/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/main.jsx",
    "./src/pages/LoginPage.jsx",
    "./src/components/NavBar.jsx",
    "./src/pages/HomePage.jsx",
    "./src/pages/IfcDialog.jsx",
    "./src/pages/ProjectPage.jsx",
    "./src/pages/CreatePage.jsx",
    "./src/components/BarChart.jsx",
    "./src/components/AwardCard.jsx",
    "./src/Layout.jsx",
    "./src/components/SankeyChart.jsx",
    "./src/pages/DraftPage.jsx",
    "./src/components/HistoryTable.jsx",
    "./src/components/Stepper.jsx",
    "./src/components/MaterialTable.jsx",
    "./src/pages/MaterialInfoPage.jsx",
    "./src/pages/ProjectInfoPage.jsx",
    "./src/pages/UploadConfirmationPage.jsx",
    "./src/pages/BreakdownPage.jsx",
    "./src/pages/UploadHistory.jsx",
    "./src/components/UploadTabs.jsx",
    "./src/pages/UploadOverview.jsx",
    "./src/pages/UploadComparison.jsx",
    "./src/pages/ProjectProgress.jsx",
    "./src/components/MirrorBarChart.jsx",
    "./src/pages/MaterialDialog.jsx",
    "./src/pages/ErrorHandlingPage.jsx",
    "./src/components/Sankey2.jsx",
    "./src/pages/ExportResults.jsx",
    "./src/pages/LoadingPage.jsx",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
